language: python
python:
  - "3.4"
addons:
  postgresql: "9.3"
install:
  - pip install wheel
  - pip install -r requirements.txt
  - pip install -r requirements-testing.txt
  - npm install
before_script:
  - createdb -U postgres pastry
  - python manage.py migrate --noinput
  - python manage.py createsuperuser --username=travis --email=travis@localhost --noinput
script:
  - make dist
  - py.test
branches:
  only:
    - master
